### PR TITLE
Adding MJPEG

### PR DESCRIPTION
**Pull request by benhoff**
Hey I dug through the rkmppdec.c to see where MJPEG might need additional handling.  

I specifically looked at areas where avctx->codec_id is handled.

[I don't know that AFBC needs to be handled for MJEPG.](https://github.com/nyanmisaka/ffmpeg-rockchip/blob/9efe5bcff082d6538702d01c9b7126f40da27361/libavcodec/rkmppdec.c#L245)

[I don't believe that there is such a thing as sample aspect ratio.](https://github.com/nyanmisaka/ffmpeg-rockchip/blob/9efe5bcff082d6538702d01c9b7126f40da27361/libavcodec/rkmppdec.c#L589)

[I don't think there's an issue with mastering display for MJPEG.](https://github.com/nyanmisaka/ffmpeg-rockchip/blob/9efe5bcff082d6538702d01c9b7126f40da27361/libavcodec/rkmppdec.c#L596)

FFMPEG and container formats is not my jam however. Is there something I'm missing that needs to be added or addressed? Happy to take a swing at this.

### CODE REVIEW

**Comment by nyanmisaka** [comment]
This won't work, you can try it out.

Unlike other codecs, MJPEG decoding in MPP uses a special [advanced interface](https://github-com.translate.goog/rockchip-linux/mpp/issues/586?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp), so it can't reuse existing logic.

**Comment by benhoff** [comment]
Would it make sense to port this code into the existing code base?

https://github-com.translate.goog/rockchip-linux/mpp/issues/592?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp#issuecomment-2101716446

```
    if (isAdvanced)
    {
        //! 设置输出frame的buffer
        MppBuffer frm_buf = NULL;
        ret = dec_buf_mgr_init(&(loop_data.buf_mgr));
        if (ret != MPP_OK)
        {
            LOGD("dec_buf_mgr_init failed\n");
        }
        ret = mpp_frame_init(&frame); /* output frame */
        if (ret != MPP_OK)
        {
            LOGD("mpp_frame_init failed\n");
        }
        loop_data.frm_grp = dec_buf_mgr_setup(loop_data.buf_mgr, MPP_ALIGN(width_mpp, 16) * MPP_ALIGN(height_mpp, 16) * 4, 4, MPP_DEC_BUF_HALF_INT);
        if (!(loop_data.frm_grp))
        {
            LOGD("failed to get buffer group for input frame ret %d\n", ret);
            ret = MPP_NOK;
        }
        ret = mpp_buffer_get(loop_data.frm_grp, &frm_buf, MPP_ALIGN(width_mpp, 16) * MPP_ALIGN(height_mpp, 16) * 4);
        if (ret != MPP_OK)
        {
            LOGD("failed to get buffer for input frame ret %d\n", ret);
        }
        mpp_frame_set_buffer(frame, frm_buf);
    }
```

**Comment by nyanmisaka** [comment]
This makes sense, but in practice it would be better to unify the interfaces in MPP.

**Comment by benhoff** [comment]
Is it the idea that the simple api is using somewhat syncronous interfaces and the advanced is using more of an epoll?


So is the idea that we need to flip to more of an epoll based code this line of code?
https://github.com/rockchip-linux/mpp/blob/239e15eaebf98f68c0093b00ff8108d23b0147e7/test/mpi_dec_test.c#L336

Rather than using the function `decode_get_frame` as it's currently leveraged?

Is the thought that once you've made the change to the advanced interface you would use that as the mainline for all code?

Sorry to prod on this, I'm trying to get something out to market and did not expect this much complexity, so I'm trying to figure out if I can patch out of this or if I should figure out a workaround.

Note to myself: probably need to follow this line of code to change output format before JPEG decoding:
[mpi_dec_test.c ](https://github.com/rockchip-linux/mpp/blob/239e15eaebf98f68c0093b00ff8108d23b0147e7/test/mpi_dec_test.c#L420)

**Comment by nyanmisaka** [comment]
> Is it the idea that the simple api is using somewhat syncronous interfaces and the advanced is using more of an epoll?

https://github.com/rockchip-linux/mpp/blob/239e15eaebf98f68c0093b00ff8108d23b0147e7/inc/rk_mpi.h#L50-L52

> So is the idea that we need to flip to more of an epoll based code similar to this block of code?

Nope. According to RK developers, the simple interface is recommended anyway. 

But the MJPEG decode is an exception, they have not yet implemented the simple interface for it (the simple interface calls [MppTask/advanced](https://github.com/rockchip-linux/mpp/blob/develop/doc/design/4.mpp_task.txt) interface internally).

**Comment by benhoff** [comment]
I ended up purchasing a USB3.0 capture card that didn't need mjpeg decoding.

I sat down several times to try and commit something, but the complexity of the existing implementation of ffmpeg-rockchip and available examples of mpp outstrip my skills to try and pull something clean together.

**Pull request closed without merging**
